# PathError



``` python
PathError(self, message, path, key=None, incomplete=False, incorrect=False)
```

Mapping key not found.

#### Arguments:
- **self**
- **message**
- **path** (_str_)
- **key** (_str_ = None)
- **incomplete** (_bool_ = False)
- **incorrect** (_bool_ = False)



### Inherited

BaseException.\_\_cause__ :black_small_square: BaseException.\_\_context__ :black_small_square: BaseException.\_\_delattr__ :black_small_square: BaseException.\_\_getattribute__ :black_small_square: BaseException.\_\_reduce__ :black_small_square: BaseException.\_\_repr__ :black_small_square: BaseException.\_\_setattr__ :black_small_square: BaseException.\_\_setstate__ :black_small_square: KeyError.\_\_str__ :black_small_square: BaseException.\_\_suppress_context__ :black_small_square: BaseException.\_\_traceback__ :black_small_square: PathError.\_\_weakref__ :black_small_square: BaseException.add_note :black_small_square: BaseException.args :black_small_square: BaseException.with_traceback :black_small_square: 